configReload:
  schedule: "*/5 * * * *"
  configUrl: https://raw.githubusercontent.com/escoand/dockerfiles/fetchit.localrelay/config.yaml
targetConfigs:
- url: https://github.com/escoand/dockerfiles.git
  branch: kube
  kube:
  - name: kube
    targetPath: kube.localrelay
    schedule: "*/1 * * * *"
    pullImage: true
prune:
  All: true
  Volumes: false
  schedule: "*/1 * * * *"