[Definition]
actionban =   echo 'BAN <ip>'   | nc -w 5 -U /run/fail2ban-fw/fail2ban-fw.sock | grep -qx OK
actioncheck = echo 'CHECK'      | nc -w 5 -U /run/fail2ban-fw/fail2ban-fw.sock | grep -qx OK
actionstart = echo 'START'      | nc -w 5 -U /run/fail2ban-fw/fail2ban-fw.sock | grep -qx OK
actionstop =  echo 'STOP'       | nc -w 5 -U /run/fail2ban-fw/fail2ban-fw.sock | grep -qx OK
actionunban = echo 'UNBAN <ip>' | nc -w 5 -U /run/fail2ban-fw/fail2ban-fw.sock | grep -qx OK
