sudo: required
services:
  - docker
language: minimal

env:
    # direct hassio builds
  - TAG=i386 ARCH=$TAG \
    HAPROJECT=hassio-nextcloud \
    HABASE=$ARCH/nextcloud:apache
  - TAG=amd64 ARCH=$TAG \
    HAPROJECT=hassio-nextcloud \
    HABASE=$ARCH/nextcloud:apache
  - TAG=armhf ARCH=arm32v7 \
    HAPROJECT=hassio-nextcloud \
    HABASE=$ARCH/nextcloud:apache
  - TAG=arm64 ARCH=arm64v8 \
    HAPROJECT=hassio-nextcloud \
    HABASE=$ARCH/nextcloud:apache
    # two step builds
  - TAG=i386 ARCH=$TAG \
    PROJECT=nextcloud \
    HAPROJECT=hassio-$PROJECT-ext \
    HABASE=$RESULT
  - TAG=amd64 ARCH=$TAG \
    PROJECT=nextcloud \
    HAPROJECT=hassio-$PROJECT-ext \
    HABASE=$RESULT
  - TAG=armhf ARCH=arm32v7 \
    PROJECT=nextcloud \
    HAPROJECT=hassio-$PROJECT-ext \
    HABASE=$RESULT
  - TAG=arm64 ARCH=arm64v8 \
    PROJECT=nextcloud \
    HAPROJECT=hassio-$PROJECT-ext \
    HABASE=$RESULT

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

script: |
  if [ -n "$PROJECT" ]; then
    RESULT=${RESULT:-$DOCKER_USER/$PROJECT-$TAG}
    docker build --pull --build-arg ARCH=$ARCH --build-arg ARCHALIAS=$TAG -t $RESULT $PROJECT &&
    docker push $RESULT ||
    exit 1
  fi
  if [ -n "$HABASE" ]; then
    HARESULT=${HARESULT:-$DOCKER_USER/$HAPROJECT-$TAG}
    docker build --pull --build-arg BUILD_FROM=$HABASE --build-arg ARCHALIAS=$TAG -t $HARESULT ${HAPROJECT:-hassio-$PROJECT} &&
    docker push $HARESULT ||
    exit 2
  fi
