sudo: required
services:
  - docker
language: minimal

env:
  - PROJECT1=nextcloud  PROJECT2=hassio-$PROJECT1  TAG=i386   ARCH=$TAG
  - PROJECT1=nextcloud  PROJECT2=hassio-$PROJECT1  TAG=amd64  ARCH=$TAG
  - PROJECT1=nextcloud  PROJECT2=hassio-$PROJECT1  TAG=armhf  ARCH=arm32v7
  - PROJECT1=nextcloud  PROJECT2=hassio-$PROJECT1  TAG=arm64  ARCH=arm64v8

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - |
    docker build --pull --build-arg ARCH=$ARCH --build-arg ARCHALIAS=$TAG  -t $DOCKER_USER/$PROJECT1:$TAG $PROJECT1 &&
    docker build --pull --build-arg BUILD_FROM=$DOCKER_USER/$PROJECT1:$TAG -t $DOCKER_USER/$PROJECT2-$TAG $PROJECT2

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $DOCKER_USER/$PROJECT1:$TAG
  - docker push $DOCKER_USER/$PROJECT2-$TAG
