sudo: required
services:
  - docker
language: minimal

env:
  - ARCH=i386     TAG=$ARCH    QEMUTAG=$ARCH  PROJECT=nextcloud
  - ARCH=amd64    TAG=$ARCH    QEMUTAG=$ARCH  PROJECT=nextcloud
  - ARCH=arm32v7  TAG=armhf    QEMUTAG=$TAG   PROJECT=nextcloud
  - ARCH=arm64v8  TAG=aarch64  QEMUTAG=arm64  PROJECT=nextcloud
  - ARCH=i386     TAG=$ARCH    QEMUTAG=$ARCH  PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud
  - ARCH=amd64    TAG=$ARCH    QEMUTAG=$ARCH  PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud
  - ARCH=arm32v7  TAG=armhf    QEMUTAG=$TAG   PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud
  - ARCH=arm64v8  TAG=aarch64  QEMUTAG=arm64  PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud

before_install:
  - sudo apt update
  - sudo apt install -y jq

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

script: |
  if [ -d "$PROJECT" ]; then
    RESULT=$DOCKER_USER/$PROJECT:$TAG
    docker build --pull --build-arg ARCH=$ARCH --build-arg QEMUTAG=$QEMUTAG -t $RESULT $PROJECT &&
    docker push $RESULT ||
    exit 1
  fi
  if [ -d "hassio-$PROJECT" ]; then
    HAPROJECT=hassio-$PROJECT
    HADOCKER=${HADOCKER:-$HAPROJECT}
    HABASE=$(jq -r ".build_from.$TAG" $HAPROJECT/build.json)
    HARESULT=$(jq -r '.image+":"+.version' $HAPROJECT/config.json | sed "s|{arch}|$TAG|g")
    docker build --pull --build-arg BUILD_FROM=$HABASE --build-arg QEMUTAG=$QEMUTAG -t $HARESULT $HADOCKER &&
    docker push $HARESULT ||
    exit 2
  fi
