sudo: required
services:
  - docker
language: minimal

env:
  - TAG=i386     QEMUTAG=$TAG   PROJECT=hassio-nextcloud
  - TAG=amd64    QEMUTAG=$TAG   PROJECT=hassio-nextcloud
  - TAG=armhf    QEMUTAG=$TAG   PROJECT=hassio-nextcloud
  - TAG=aarch64  QEMUTAG=arm64  PROJECT=hassio-nextcloud
  #- TAG=i386     QEMUTAG=$TAG   PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud
  #- TAG=amd64    QEMUTAG=$TAG   PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud
  #- TAG=armhf    QEMUTAG=$TAG   PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud
  #- TAG=aarch64  QEMUTAG=arm64  PROJECT=nextcloud-ext  HADOCKER=hassio-nextcloud

before_install:
  - sudo apt update
  - sudo apt install -y jq

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

script: |
  HADOCKER=${HADOCKER:-$PROJECT}
  HABASE=$(jq -r '.build_from[env.TAG]' $PROJECT/build.json)
  HARESULT=$(jq -r '.image+":"+.version|sub("{arch}";env.TAG)' $PROJECT/config.json)
  docker build --pull --build-arg BUILD_FROM=$HABASE --build-arg QEMUTAG=$QEMUTAG -t $HARESULT $HADOCKER &&
  docker push $HARESULT
