sudo: required
services:
  - docker
language: minimal

env:
    # direct hassio builds
  - ARCH=i386     TAG=$ARCH    QEMUTAG=$ARCH                     HAPROJECT=hassio-nextcloud
  - ARCH=amd64    TAG=$ARCH    QEMUTAG=$ARCH                     HAPROJECT=hassio-nextcloud
  - ARCH=arm32v7  TAG=armhf    QEMUTAG=$TAG                      HAPROJECT=hassio-nextcloud
  - ARCH=arm64v8  TAG=aarch64  QEMUTAG=arm64                     HAPROJECT=hassio-nextcloud
    # two step builds
  - ARCH=i386     TAG=$ARCH    QEMUTAG=$ARCH  PROJECT=nextcloud  HAPROJECT=hassio-$PROJECT-ext
  - ARCH=amd64    TAG=$ARCH    QEMUTAG=$ARCH  PROJECT=nextcloud  HAPROJECT=hassio-$PROJECT-ext
  - ARCH=arm32v7  TAG=armhf    QEMUTAG=$TAG   PROJECT=nextcloud  HAPROJECT=hassio-$PROJECT-ext
  - ARCH=arm64v8  TAG=aarch64  QEMUTAG=arm64  PROJECT=nextcloud  HAPROJECT=hassio-$PROJECT-ext

before_install:
  - sudo apt update
  - sudo apt install -y jq

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

script: |
  if [ -n "$PROJECT" ]; then
    RESULT=$DOCKER_USER/$PROJECT:$TAG
    docker build --pull --build-arg ARCH=$ARCH --build-arg QEMUTAG=$QEMUTAG -t $RESULT $PROJECT &&
    docker push $RESULT ||
    exit 1
  fi
  if [ -n "$HAPROJECT" ]; then
    HABASE=$(jq -r ".build_from.$TAG" $HAPROJECT/build.json)
    HARESULT=$(jq -r ".image" $HAPROJECT/config.json | sed "s|{arch}|$TAG|g")
    docker build --pull --build-arg BUILD_FROM=$HABASE --build-arg QEMUTAG=$QEMUTAG -t $HARESULT $HAPROJECT &&
    docker push $HARESULT ||
    exit 2
  fi
