sudo: required
services:
  - docker
language: minimal

env:
  - PROJECT1=nextcloud  PROJECT2=hassio-nextcloud  TAG=i386     ARCH=i386
  - PROJECT1=nextcloud  PROJECT2=hassio-nextcloud  TAG=amd64    ARCH=amd64
  - PROJECT1=nextcloud  PROJECT2=hassio-nextcloud  TAG=armhf    ARCH=arm32v7
  - PROJECT1=nextcloud  PROJECT2=hassio-nextcloud  TAG=aarch64  ARCH=arm64v8

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - |
    docker build --pull --build-arg ARCH=$ARCH                             -t $DOCKER_USER/$PROJECT1-$TAG $PROJECT1 &&
    docker build --pull --build-arg BUILD_FROM=$DOCKER_USER/$PROJECT1-$TAG -t $DOCKER_USER/$PROJECT2-$TAG $PROJECT2

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $DOCKER_USER/$PROJECT1-$TAG
  - docker push $DOCKER_USER/$PROJECT2-$TAG
