sudo: required
services:
  - docker
language: minimal

env:
  - PROJECT=nextcloud         TAG=i386     ARCH=i386
  - PROJECT=nextcloud         TAG=amd64    ARCH=amd64
  - PROJECT=nextcloud         TAG=armhf    ARCH=arm32v7
  - PROJECT=nextcloud         TAG=aarch64  ARCH=arm64v8
  - PROJECT=hassio-nextcloud  TAG=i386     ARCH=i386
  - PROJECT=hassio-nextcloud  TAG=amd64    ARCH=amd64
  - PROJECT=hassio-nextcloud  TAG=armhf    ARCH=arm32v7
  - PROJECT=hassio-nextcloud  TAG=aarch64  ARCH=arm64v8

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker build --pull --build-arg ARCH=$ARCH -t $DOCKER_USER/$PROJECT:$TAG $PROJECT

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $DOCKER_USER/$PROJECT:$TAG
