env:
  global:
    - secure: NeGqAJYmojDU34bSUOCjIruEqQ+cEbMhPe3Ed2lUclpjDfRCs693f7QqU9uW/OX13SqEU0ODmNOo8DMEw+HwvT6olslx3OtDUVIBuEFnGaJcrb2SRfSu5+FRytEB/9HuZWx4nsByJBl27+YeQQtiq1Qaw4uA42I6nG93GwOMAZmL1PJcCPXdm8K+tIhbfj+zxH/gRte503QY47gMP2tMPEy2X3TfTe0Dr5BntIXk8GerJiXeQWhy6YacKhUn5BUpSxm+R2bpPnsV1SN2d2iKnHe3hLNbu4HIXtAK6oB6n78HzzLESsDnehk0PT+kdqC7DTNYO6zCukEjSjmp4ZiJH5G9VhLGksYdnEUEZ/ovUanY/PRIpxyCIWyIevF49921pM4b9u3h2S5Wb9y3OYfDXo1AKbjPfp3RK5IfsTfrogMmTjIP4Y3BMLmeCt+9B078jNcyASki69qTacUBrjBvc7tyWYqsD2b9qWzn0zi3icybAfoYB36MwnDQLvjSXLF/HKmkqf4y7jcPUfUisAePoMAtItdWT1udy3COpqh78m60CQMzUHtAj6X6npwnyVjhnPNXx4KQAbm2Wblauw+ZKriN5hpJDM41g+xdMe/+CzvBhJhOEBSDGDgX6A4zsijct97HTA9jt+hZhLkqJWoPz77qRRCwHaGaqA8V/9ITbBk=
    - secure: J1KF1Ly5T64H5CqlVSbev69X5SNAj28tOVZ/y1ysDZdXIHyd6lgdbXUXvaYH+XIECl3YVQyEBboe1TkD3KXpDHMPgqllf5DBNKQzbvlp/fOGLiwF9Zuw4wIWtOW/nV6pd74UdlGX3b9m9JHgZpzv5HDYS2zOfD+e/oYb6dmI+APlovGQpjfvy7syCeIaL1hNa9emd74TDjbtX/XKDh7b34uTs3odUAggTDTt/Chq0k1D7BgVuhHXZMVuGFQt5Ox2m7ORg0UQ8qWuBaD41u13spKWIKH8iqxtyTDTqD/TZiCPbnWpZ8Kh7MptYpfKv2BLnpHo0NjJxH25jRqwyq5babAjfs4Q20L4vrDkLHgjTImmiwCNLYpt3Q19tpaPmszzxakSQZSOZL33j135n56asJthTelWBcPHdPvYrTb92hLkHK4rQhujMVjhI5IGeLvpJMjd6mSOJjkBehs+aPET7DwkXDNERhnB6AgoaopMH1CtaMzJnXkrcMUDA53226tKNE5Yoa9Ic39xi4wNm29H5q3Fc7LGGhw6VmNSRv4tGilmsm2QAuMO1mskmTy9UUIG90/q/mrIZCGNm1m9CBma3MZVEoXivoJN8oFd5bD4tN67kLGXy/OZC7jdqtI405S7YX/IKH+JHgSns/rClh4Cg3TV/pXRqvBxdY8ZC2E7rFI=
    - secure: R+dqySCp7xxJ6sD1xbz7lf3bBFXI9nagdp1RSHEIny1bKzdie/2twgn+dtfKog+/MTdEaly29aKKPsJMCHbTqNNRdSrKEtGPP67CKapaYMooZs2wPaxa/J0FtrPftts5PBB3kvsTOxsMFMzBQ3klrVG9wsPp4WDC5r0MlQhpV5zZsArFZUCHH+oZb7MUo3D9Mmk6aVA7S1F490wrcO3VMtYI5/YVKRdcXMBHajcXfK46M4uRteN7tsnBH82ZdLLyhg0K5mU+sTDqxTDgoHGJNvbHf4zhSp2T+KOVwk9K2pFP3mNxRmYST7acMwe14lRL36tzru1ieywoNTL+6Fb/nFAyaBDIBu6xthVDGa31HDJ51GLS1bMDdPmDuaXIR4DRK85ZHTrbMnqzT0xxVny9bjBOr79y+u/P8qa/f26EBDTteNKI26RqPMEsNDJ1x2V7YtMPgmSrrWlql6WGzyxOXpOLleG+wwNFMNjlLwAWXoO88ozln58Z/ij4ZMB9aJ1GadofSzPgVlKWASYscS0PKuj057DWla7kuapXMeXC2TstSoi4/Wco09vBeSx798XUZ/lSkQXwKAtS60NUwgaltJ9P/e27EFYJFxtLrjtAb8MFlpWSwV3d1VbB6//y0j0FmanbjL/rPKYYLds/Ht/1WhfqWcRU1gN2CMBE4d7wsow=

  matrix:
    #- PROJECT=nextcloud           ARCH=amd64
    #- PROJECT=nextcloud           ARCH=armhf
    #- PROJECT=hass_ble_scanner    ARCH=amd64
    #- PROJECT=hass_ble_scanner    ARCH=armhf
    #- PROJECT=hass_switch_counter ARCH=armhf
    - PROJECT=nextcloudpi         ARCH=amd64
    - PROJECT=nextcloudpi         ARCH=armhf

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker build --pull --build-arg ARCH=$ARCH -t $DOCKER_USER/$PROJECT:$ARCH $PROJECT

deploy:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USER/$PROJECT:$ARCH