sudo: required
services:
  - docker
language: minimal

env:
  - PROJECT=nextcloud    TAG=latest
  - PROJECT=nextcloudpi  TAG=x86
  - PROJECT=nextcloudpi  TAG=armhf

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker build --pull --build-arg ARCH=$TAG -t $DOCKER_USER/$PROJECT:$TAG $PROJECT

after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $DOCKER_USER/$PROJECT:$TAG
