sudo: required
services:
  - docker
language: minimal

env:
  global:
    - ADDON=hassio-nextcloud
    - ADDON=hassio-nextcloud-ext
  jobs:
    - ARCH=i386     QEMUARCH=$ARCH
    - ARCH=amd64    QEMUARCH=$ARCH
    - ARCH=armhf    QEMUARCH=$ARCH
    - ARCH=armv7    QEMUARCH=armhf
    - ARCH=aarch64  QEMUARCH=arm64

install:
  - sudo apt update
  - sudo apt install -y jq

before_script:
  - BUILD_FROM=$(jq -r '.build_from[env.ARCH]' $ADDON/build.json)
  - BUILD_VERSION=$(jq -r '.version' $ADDON/config.json)
  - FINAL_IMAGE=$(jq -r '.image+":"+.version|sub("{arch}";env.ARCH)' $ADDON/config.json)
  - [ "$TRAVIS_CPU_ARCH" = arm64 ] && sed -ie '/multiarch/d' $ADDON/Dockerfile
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

script: |
  docker build --pull \
    --build-arg BUILD_FROM=$BUILD_FROM --build-arg QEMUARCH=$QEMUARCH \
    --label io.hass.version="$BUILD_VERSION" --label io.hass.type="addon" --label io.hass.arch="$ARCH" \
    -t $FINAL_IMAGE $ADDON &&
  docker push $FINAL_IMAGE
