#cloud-config
timezone: Europe/Berlin
users:
  - name: horst
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - >-
        ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDp7Ij6tMK/6enpXE6qftq5PmPZL9HT6/iO975Bt9UjUezptGHIjh1hQ1z2ZOvC9r/Yuvu6X7g3PntFadwE5LMrmBL8Wte5unIcWLORoH7ha1lGDuOWKVyfuuhDzZ9aUHFMQ2hmFzShEHACub/gIAqLIGjQUlNykK32mGz8YSFh4FBELmDWbZXK7hmA34l4I1Hojd/nN0IZk4qQHVVNoUdzy77ZLO6sJbtlOD8SoQqaS0PRg+KFtG/LlKW1jTTUL4YXI80swNMPtyquXgRa+cn6EbdxMTJkmbQMS9fttLneOdPL5DGKu/2cRNjEM+FbIQtFePr1dEicNxMw7UdlRrRj
        desktop
      - >-
        ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDRLWPBKT1/DVBg4RkwCxF/S00fl/NHEAWf+T+2a0/gM8mYd2KZKUqHAgLMk1v/2mExifBW/LT/vtQnD89bxHOpDP+jxjfYLDMoli05vfn/hwImte/lGbNPY6gZjTUm7ujcz8c0aoNUOO7WAlvkqPZi2+bFq+9YiVCiIVpy9vefgjqcFRZXVow1PSin/Kp3SxuPY1BniVm7ZdkENdnisbM5yCCOxzLNbGVDMWE9lhHgdtp629UBJ30cWW4Zn/oBKkLgoRZ1zkAjEyc1yBUWnkZJnbyQ4T0EJmHWcd9TqlpFi2P313QrTa0se1Xw2PzOhIs/UnIFflDe0sY4Gq0s0TVV
        phone
      - >-
        ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABgQC7DLJAxJNbTKYipUMVlMLPTH9CSGY0D47YgtMXP54Ms3MrUPWDw+QKRKJIKYcJp7rXVAeDLRJfoO56JhjiqyOohven2CJ9dfNvqG9V6ecimsXL8JGMRwSo+EmcadAitexeQ9VWrOPN2u+vKVZULMQY2TO+Q4zAg4x37Egm722weOSljAKkHc2ou376qXa8liAr6GueUx2XflRBTnYCrycuqz0WpAf9ip1CyPJFGk6QwMziY8LmqmQ5YKCVuxGSQXLJeIOobSiLoZECv3/U58eUBFZhR3IpWOtf2qgyClECNYwWhh5zvtaMmJYZDwLZSRAb2UQGRpzI5WjWbenGoILk7YvJiDRIw7F8X+z/kxKQPGxb9rRJ3ovbzYIPe9xZhpyYvHExJyChIx7rpHc0GlpUtRfIVt19TuzwwLOvag62EznyB0/O7BlHsroD+LPe1lGpJx1dtTXCAxgqF40/Z97gXE2MpwCjTp7+98amHK49bfzLRgVMQHdrwL8D+gkMca8=
        homeassistant
packages:
  - firewalld
  - podman
package_update: true
package_upgrade: true
write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    content: |
      AllowAgentForwarding no
      AllowTcpForwarding no
      AllowGroups admin
      AuthorizedKeysFile .ssh/authorized_keys
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      MaxAuthTries 2
      PasswordAuthentication no
      PermitRootLogin no
      #Port 2222
      X11Forwarding no
  - path: /usr/local/bin/startcontainer
    permissions: 0755
    content: |
      #!/bin/sh
      systemctl --user status "$1" |
      sed -n '/ ExecStart=/{ s/.* ExecStart=//; s/(code=.*//; s/ -d//; p; }' |
      sh -s
runcmd:
  # disable syslog
  - systemctl disable --now syslog.socket rsyslog.service
  # allow privileged ports
  - sysctl net.ipv4.ip_unprivileged_port_start=80
  # fail2ban handler
  - curl -LOsS --output-dir /usr/local/bin/ https://raw.githubusercontent.com/escoand/dockerfiles/master/fail2ban-fw/fail2ban-fw.sh
  - curl -LOsS --output-dir /etc/systemd/system/ https://raw.githubusercontent.com/escoand/dockerfiles/master/fail2ban-fw/fail2ban-fw.socket https://raw.githubusercontent.com/escoand/dockerfiles/master/fail2ban-fw/fail2ban-fw@.service
  - chmod 0755 /usr/local/bin/fail2ban-fw.sh
  - systemctl daemon-reload
  - systemctl enable --now fail2ban-fw.socket
  # user services
  - setsebool -P container_manage_cgroup true
  - loginctl enable-linger horst
  - mkdir -p ~horst/.quadit ~horst/.config/containers/systemd
  - curl -LsS -o ~horst/.quadit/config.yaml https://raw.githubusercontent.com/escoand/dockerfiles/master/quadit.yaml
  - curl -LOsS --output-dir ~horst/.config/containers/systemd/ https://raw.githubusercontent.com/ubiquitous-factory/quadit/main/deploy/quadit.container
  - chown -R "horst:" ~horst/
  - su - horst -c "systemctl --user daemon-reload"
  - su - horst -c "systemctl --user enable --now podman.socket"
  - su - horst -c "systemctl --user start quadit"
