#cloud-config
timezone: Europe/Berlin
users:
  - name: horst
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
packages:
  - firewalld
  - git
  - podman
package_update: true
package_upgrade: true
write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    content: |
      AllowAgentForwarding no
      AllowTcpForwarding no
      AllowUsers horst
      AuthorizedKeysCommand curl -LsS https://github.com/escoand.keys
      AuthorizedKeysFile .ssh/authorized_keys
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      #MaxAuthTries 2
      PasswordAuthentication no
      PermitRootLogin no
      #Port 2222
      X11Forwarding no
  - path: /usr/local/bin/startcontainer
    permissions: 0755
    content: |
      #!/bin/sh
      systemctl --user status "$1" |
      sed -n '/ ExecStart=/{ s/.* ExecStart=//; s/(code=.*//; s/ -d//; p; }' |
      sh -s
runcmd:
  # disable syslog
  - systemctl disable --now syslog.socket rsyslog.service
  # allow privileged ports
  - sysctl net.ipv4.ip_unprivileged_port_start=80
  # fail2ban handler
  - curl -LOsS --output-dir /usr/local/bin/ https://raw.githubusercontent.com/escoand/dockerfiles/master/fail2ban-fw/fail2ban-fw.sh
  - curl -LOsS --output-dir /etc/systemd/system/ https://raw.githubusercontent.com/escoand/dockerfiles/master/fail2ban-fw/fail2ban-fw.socket https://raw.githubusercontent.com/escoand/dockerfiles/master/fail2ban-fw/fail2ban-fw@.service
  - chmod 0755 /usr/local/bin/fail2ban-fw.sh
  - systemctl daemon-reload
  - systemctl enable --now fail2ban-fw.socket
  # user services
  - setsebool -P container_manage_cgroup true
  - loginctl enable-linger horst
  - mkdir -p ~horst/.quadit ~horst/.config/containers/systemd
  - curl -LsS -o ~horst/.quadit/config.yaml https://raw.githubusercontent.com/escoand/dockerfiles/master/quadit.yaml
  - curl -LOsS --output-dir ~horst/.config/containers/systemd/ https://raw.githubusercontent.com/ubiquitous-factory/quadit/main/deploy/quadit.container
  - chown -R "horst:" ~horst/
  - curl -LsS https://raw.githubusercontent.com/escoand/dockerfiles/master/secrets.init.sh | su - horst -c "bash -s"
  - su - horst -c "export XDG_RUNTIME_DIR=/run/user/1000; systemctl --user daemon-reload; systemctl --user enable --now podman.socket; systemctl --user start quadit"
