apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
data:
  nextcloud_domain: Y2xvdWQubG9jYWxob3N0
  nextcloud_db_name: bmV4dGNsb3Vk
  nextcloud_db_password: bmV4dGNsb3Vk
  nextcloud_db_user: bmV4dGNsb3Vk
