apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: wordpress1
data:
  WORDPRESS_DB_NAME=
  WORDPRESS_DB_PASSWORD=
  WORDPRESS_DB_USER=
  WORDPRESS_TABLE_PREFIX=
  WORDPRESS_AUTH_KEY=
  WORDPRESS_AUTH_SALT=
  WORDPRESS_LOGGED_IN_KEY=
  WORDPRESS_LOGGED_IN_SALT=
  WORDPRESS_NONCE_KEY=
  WORDPRESS_NONCE_SALT=
  WORDPRESS_SECURE_AUTH_KEY=
  WORDPRESS_SECURE_AUTH_SALT=
