apiVersion: v1
kind: Pod
metadata:
  name: caddy
spec:
  containers:
    - name: app
      image: docker.io/lucaslorentz/caddy-docker-proxy:2.9.1-alpine
      ports:
        - containerPort: 80
          hostPort: 8080
        - containerPort: 443
          hostPort: 8443
        - containerPort: 443
          hostPort: 8443
          protocol: UDP
        # because of firewall port-forwarding on internal interface
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
      securityContext:
        privileged: true
      livenessProbe:
        # httpGet uses curl, which is not available
        tcpSocket:
          port: 80
      envFrom:
        - secretRef:
            name: caddy
      volumeMounts:
        - name: caddy
          mountPath: /data
        - name: docker_sock
          mountPath: /var/run/docker.sock:ro
  volumes:
    - name: caddy
      persistentVolumeClaim:
        claimName: caddy
    - name: docker_sock
      hostPath:
        path: /run/user/1000/podman/podman.sock
        type: Socket
