apiVersion: v1
kind: Pod
metadata:
  name: claper
  labels:
    caddy: "{$CLAPER_DOMAIN}"
    caddy.reverse_proxy: "{{upstreams 4000}}"
spec:
  containers:
    - name: app
      image: ghcr.io/claperco/claper:2.0.1
      command:
        - sh
        - -c
        - env
      livenessProbe:
        httpGet:
          port: 4000
          httpHeaders:
          - name: Host
            value: claper.localhost
        initialDelaySeconds: 20
      env:
        - name: CLAPER_DOMAIN
          valueFrom:
            secretKeyRef:
              name: caddy
              key: CLAPER_DOMAIN
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_DB
        - name: POSTRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_USER
        # assemble env vars
        - name: BASE_URL
          value: http://$(CLAPER_DOMAIN)
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
      envFrom:
        - secretRef:
            name: claper