apiVersion: v1
kind: Pod
metadata:
  name: claper
  labels:
    caddy: "{$CLAPER_DOMAIN}"
    caddy.reverse_proxy: "{{upstreams 4000}}"
spec:
  containers:
    - name: app
      image: ghcr.io/claperco/claper:2.0.1
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - >-
              curl -isS -m1 --http1.1 \
                -H "Connection: upgrade" \
                -H "Origin: $BASE_URL" \
                -H "Sec-WebSocket-Key: LQ==" \
                -H "Sec-WebSocket-Version: 13" \
                -H "Upgrade: websocket" \
                "http://localhost:4000/live/websocket" 2>&1 |
                grep -Fq "HTTP/1.1 101"
        httpGet:
          port: 4000
        initialDelaySeconds: 20
        timeoutSeconds: 2
      envFrom:
        - secretRef:
            name: claper
      volumeMounts:
        - name: claper
          mountPath: /app/uploads
  volumes:
    - name: claper
      persistentVolumeClaim:
        claimName: claper
