apiVersion: v1
kind: Pod
metadata:
  name: claper
  labels:
    caddy: "{$CLAPER_DOMAIN}"
    caddy.reverse_proxy: "{{upstreams 4000}}"
spec:
  containers:
    - name: app
      image: ghcr.io/claperco/claper:latest
      livenessProbe:
        httpGet:
          port: 4000
          httpHeaders:
          - name: Host
            value: claper.localhost
      env:
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: caddy
              key: CLAPER_DOMAIN
        - name: SECRET_KEY_BASE
          value: "1234567890123456789012345678901234567890123456789012345678901234"
        - name: DATABASE_URL
          value: postgres://claper:claper@postgres:5432/claper