apiVersion: v1
kind: Pod
metadata:
  name: claper
  labels:
    caddy: "{$NEXTCLOUD_DOMAIN}"
    caddy.handle_path: "/claper/*"
    caddy.handle_path.reverse_proxy: "{{upstreams 4000}}"
spec:
  containers:
    - name: app
      image: ghcr.io/claperco/claper:latest
      livenessProbe:
        httpGet:
          port: 4000
          httpHeaders:
          - name: Host
            value: cloud.localhost
      env:
        - name: SECRET_KEY_BASE
          value: "1234567890123456789012345678901234567890123456789012345678901234"
        - name: BASE_URL
          value: http://cloud.localhost
        - name: DATABASE_URL
          value: postgres://claper:claper@postgres:5432/claper