apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dozzle
spec:
  template:
    metadata:
      labels:
        caddy: "{$NEXTCLOUD_DOMAIN}"
        caddy.handle: "/dozzle/*"
        caddy.handle.basic_auth.{$DOZZLE_USER}: "{$DOZZLE_PASSWORD}"
        caddy.handle.reverse_proxy: "{{upstreams 8080}}"
    spec:
      containers:
        - name: app
          image: docker.io/amir20/dozzle:v8.1.2
          livenessProbe:
            exec:
              command: ["/dozzle", "healthcheck"]
          securityContext:
            privileged: true
          env:
            - name: DOZZLE_BASE
              value: /dozzle
            - name: DOZZLE_ENABLE_ACTIONS
              value: "true"
            - name: DOZZLE_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - name: docker_sock
              mountPath: /var/run/docker.sock:ro
      volumes:
        - name: docker_sock
          hostPath:
            path: /run/user/1000/podman/podman.sock
            type: Socket
