apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: app
      image: docker.io/library/postgres:16.4-alpine
      livenessProbe:
        exec:
          command:
            - pg_isready
            - "-q"
            - "-d"
            - "$POSTGRES_DB"
            - "-U"
            - "$POSTGRES_USER"
      envFrom:
        - secretRef:
            name: postgres
      volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres
      persistentVolumeClaim:
        claimName: postgres

