apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: app
      image: docker.io/library/redis:7.4.1-alpine
      args:
        - --appendonly no
        - --protected-mode no
        - --save ""
      livenessProbe:
        exec:
          command: ["redis-cli", "--raw", "incr", "ping"]
      resources:
        limits:
          memory: 500Mi
