apiVersion: v1
kind: Pod
metadata:
  name: wordpress1
  labels:
    caddy: "{$WORDPRESS1_DOMAIN}"
    caddy.reverse_proxy: "{{upstreams}}"
spec:
  containers:
    - name: app
      image: docker.io/library/wordpress:6.6.1-apache
      livenessProbe:
        httpGet:
          port: 80
      env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
      envFrom:
        - secretRef:
            name: wordpress1
      volumeMounts:
        - name: wordpress1
          mountPath: /var/www/html/wp-content:z
  initContainers:
    - name: init-db
      image: docker.io/library/mariadb:11.4.3
      command:
        - sh
        - -c
        - |-
          cat <<EOF | mariadb -h mariadb -p"$MARIADB_ROOT_PASSWORD"
          CREATE DATABASE IF NOT EXISTS $WORDPRESS_DB_NAME;
          CREATE USER IF NOT EXISTS '$WORDPRESS_DB_USER'@'%' IDENTIFIED BY '$WORDPRESS_DB_PASSWORD';
          GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_DB_USER'@'%';
          FLUSH PRIVILEGES;
          EOF
      envFrom:
        - secretRef:
            name: mariadb
        - secretRef:
            name: wordpress1
  volumes:
    - name: wordpress1
      persistentVolumeClaim:
        claimName: wordpress1
