apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress1
spec:
  replicas: 1
  template:
    metatdata:
      labels:
        caddy: {$WORDPRESS1_DOMAIN}
        caddy.reverse_proxy: {{upstreams}}
    spec:
      containers:
      - name: wordpress1
        image: docker.io/library/wordpress:6.5.5-apache
        livenessProbe:
          httpGet:
            port: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        envFrom:
        - secretRef:
            name: wordpress1
        volumeMounts:
        - name: wordpress1
          mountPath: /var/www/html/wp-content:z
      volumes:
      - name: wordpress1
        persistentVolumeClaim:
          claimName: wordpress1
