apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: wordpress
        image: docker.io/library/wordpress:6.5.4-apache
        livenessProbe:
          httpGet:
            port: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: wordpress_db_name
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: wordpress_db_password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: wordpress_db_user
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html/wp-content:z
      volumes:
      - name: wordpress
        persistentVolumeClaim:
          claimName: wordpress
