version: "2.4"
services:

  homeassistant:
    container_name: homeassistant
    image: docker.io/homeassistant/home-assistant:stable
    security_opt: [ label=disable ]
    restart: always
    network_mode: host
    volumes:
      - /etc/hosts:/host:ro
      - ${DATA_DIR}/homeassistant:/config
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      - /dev/ttyACM0

  esphome:
    container_name: esphome
    image: docker.io/esphome/esphome
    security_opt: [ label=disable ]
    restart: unless-stopped
    network_mode: host
    ports:
      - 6052:6052
    volumes:
      - ${DATA_DIR}/esphome:/config
    #devices:
      #- /dev/ttyUSB0

  grocy:
    container_name: grocy
    image: docker.io/linuxserver/grocy
    security_opt: [ label=disable ]
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/grocy:/config/data

  paperless:
    container_name: paperless
    image: docker.io/jonaswinkler/paperless-ng
    security_opt: [ label=disable ]
    restart: unless-stopped
    mem_limit: 1GB
    cpu_percent: 50
    links:
      - redis
    ports:
      - 8000:8000
    environment:
      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_TIME_ZONE=${TZ}
    volumes:
      - ${DATA_DIR}/paperless/data:/usr/src/paperless/data
      - ${DATA_DIR}/paperless/data:/usr/src/paperless/media
      - ${DATA_DIR}/paperless/export:/usr/src/paperless/export
      - ${DATA_DIR}/paperless/consume:/usr/src/paperless/consume

  ssh_master:
    container_name: ssh_master
    image: docker.io/alpine
    security_opt: [ label=disable ]
    restart: always
    command: sh -c '
        adduser -DH satellite;
        apk --no-cache add dropbear openssh-client &&
        mkdir -p /etc/dropbear &&
        dropbear -EFjRsw -c /bin/false
      '
    ports:
      - "${SSH_MASTER_PORT}:22"
    volumes:
      - ${DATA_DIR}/dropbear:/etc/dropbear
      - /home/admin/.ssh/authorized_keys:/home/satellite/.ssh/authorized_keys:ro
