version: "2.4"
services:

  caddy:
    container_name: caddy
    image: docker.io/library/caddy:alpine
    security_opt: [ label=disable ]
    restart: unless-stopped
    extra_hosts:
      - homeassistant:172.17.0.1
      - esphome:172.17.0.1
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN_GROCY
      - DOMAIN_HOMEASSISTANT
      - DOMAIN_NEXTCLOUD
    volumes_from:
      - nextcloud:ro
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DATA_DIR}/caddy:/data/caddy

  dyndns:
    container_name: dyndns
    image: docker.io/qmcgaw/ddns-updater
    security_opt: [ label=disable ]
    restart: unless-stopped
    environment:
      - CONFIG={"settings":[{"provider":"${DYNDNS_PROVIDER}","domain":"${DYNDNS_DOMAIN}","host":"${DYNDNS_HOST}","password":"${DYNDNS_PASSWORD}"}]}
      - LOG_LEVEL=debug
      - TZ

  nextcloud:
    container_name: nextcloud
    image: docker.io/library/nextcloud:fpm-alpine
    security_opt: [ label=disable ]
    restart: unless-stopped
    links:
      - mariadb
      - redis
    environment:
      - MYSQL_DATABASE
      - MYSQL_HOST=mariadb
      - MYSQL_PASSWORD
      - MYSQL_USER
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN_NEXTCLOUD}
      #- OVERWRITEPROTOCOL=https
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=172.17.0.0/16 172.18.0.0/16
    volumes:
      - nccontent:/var/www/html
      - ${DATA_DIR}/nextcloud/apps:/var/www/html/custom_apps
      - ${DATA_DIR}/nextcloud/config:/var/www/html/config
      - ${DATA_DIR}/nextcloud/data:/var/www/html/data
      - ./www2.conf:/usr/local/etc/php-fpm.d/www2.conf:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.nc_cron.schedule: "@every 5m"
      ofelia.job-exec.nc_cron.command: >-
        php -f /var/www/html/cron.php
      ofelia.job-exec.nc_cron.user: www-data
      ofelia.job-exec.nc_preview.schedule: "@every 30m"
      ofelia.job-exec.nc_preview.command: >-
        php -f /var/www/html/occ preview:pre-generate
      ofelia.job-exec.nc_preview.user: www-data

  mariadb:
    container_name: mariadb
    image: docker.io/yobasystems/alpine-mariadb
    security_opt: [ label=disable ]
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    command: >-
      --binlog-format=ROW
      --transaction-isolation=READ-COMMITTED
    ports:
      - 3306:3306
    volumes:
      - ${DATA_DIR}:/backup
      - ${DATA_DIR}/mariadb:/var/lib/mysql
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.db_backup.schedule: 0 0 1 * * *
      ofelia.job-exec.db_backup.command: >-
        sh -c "mysqldump -A | gzip > /backup/mariadb.sql.gz"

  redis:
    container_name: redis
    image: docker.io/redis:alpine
    security_opt: [ label=disable ]
    restart: unless-stopped
    command: redis-server --appendonly no --save ""

  samba:
    container_name: samba
    image: docker.io/dperson/samba
    security_opt: [ label=disable ]
    restart: unless-stopped
    ports:
      #- 137:137/udp
      #- 138:138/udp
      - 139:139
      - 445:445
    environment:
      - GROUPID=82
      #- NMBD=1
      - RECYCLE=1
      - SHARE1
      - SHARE2
      - SHARE3
      - SMB=1
      - TZ
      - USERID=82
    volumes:
      - ${DATA_DIR}/nextcloud/data:/data:ro
      - ${DATA_DIR}/paperless/consume:/paperless

  minidlna:
    container_name: minidlna
    image: docker.io/vladgh/minidlna
    security_opt: [ label=disable ]
    restart: unless-stopped
    environment:
      - GUID=82
      - MINIDLNA_FRIENDLY_NAME=${HOSTNAME}
      - MINIDLNA_INOTIFY=yes
      - MINIDLNA_MEDIA_DIR_1
      - MINIDLNA_MEDIA_DIR_2
      - MINIDLNA_MEDIA_DIR_3
      - MINIDLNA_MEDIA_DIR_4
      - MINIDLNA_MEDIA_DIR_5
      - MINIDLNA_MEDIA_DIR_6
      - MINIDLNA_MEDIA_DIR_7
      - MINIDLNA_MEDIA_DIR_8
      - MINIDLNA_MEDIA_DIR_9
      - MINIDLNA_ROOT_CONTAINER
      - PUID=82
    network_mode: host
    volumes:
      - ${DATA_DIR}/nextcloud/data:/data:ro

  backup:
    container_name: backup
    image: docker.io/mazzolino/restic
    security_opt: [ label=disable ]
    hostname: ${HOSTNAME}
    restart: unless-stopped
    #command: unlock
    cpu_percent: 50
    mem_limit: 500M
    environment:
      - B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY
      - BACKUP_CRON=0 0 2 * * *
      - POST_COMMANDS_FAILURE
      - POST_COMMANDS_SUCCESS
      - PRE_COMMANDS=restic unlock
      - RESTIC_BACKUP_ARGS=
          --exclude /data/docker
          --exclude /data/mariadb
          --exclude '*.log'
          --exclude 'appdata_*'
          --exclude 'files_trashbin'
          --exclude 'updater-*'
          --exclude-if-present '.nobackup'
          --exclude-if-present 'platformio.ini'
          --tag local
      - RESTIC_FORGET_ARGS=
          --group-by tag
          --keep-daily 7
          --keep-weekly 5
          --keep-monthly 12
      - RESTIC_PASSWORD
      - RESTIC_REPOSITORY
      #- RUN_ON_STARTUP=true
      - TZ
    volumes:
      - ${DATA_DIR}:/data:ro

  ssh_satellite:
    container_name: ssh_satellite
    image: docker.io/jnovack/autossh
    security_opt: [ label=disable ]
    restart: unless-stopped
    environment:
      - SSH_REMOTE_USER=satellite
      - SSH_REMOTE_HOST=${SSH_MASTER_HOST}
      - SSH_REMOTE_PORT=${SSH_MASTER_PORT}
      - SSH_STRICT_HOST_IP_CHECK=false
      - SSH_TARGET_HOST=172.17.0.1
      - SSH_TARGET_PORT=22
      - SSH_TUNNEL_PORT=${SSH_TUNNEL_PORT}
    volumes:
      - /home/admin/.ssh/id_rsa:/id_rsa:ro

  ofelia:
    container_name: ofelia
    image: docker.io/mcuadros/ofelia
    security_opt: [ label=disable ]
    restart: unless-stopped
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.reload_config.command: killall -HUP ofelia
      ofelia.job-exec.reload_config.container: ofelia
      ofelia.job-exec.reload_config.schedule: "@daily"
      ofelia.email-from: ${MAIL_RECEIVER}
      ofelia.email-to: ${MAIL_RECEIVER}
      ofelia.mail-only-on-error: "true"
      ofelia.smtp-host: ${MAIL_HOST}
      ofelia.smtp-port: ${MAIL_PORT}
      ofelia.smtp-user: ${MAIL_USER}
      ofelia.smtp-password: ${MAIL_PASSWORD}
      
  watchtower:
    container_name: watchtower
    image: docker.io/containrrr/watchtower
    security_opt: [ label=disable ]
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - TZ
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${MAIL_RECEIVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${MAIL_RECEIVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=${HOSTNAME}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${MAIL_HOST}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${MAIL_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${MAIL_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nccontent:
