version: "2.4"
services:

  traefik:
    container_name: traefik
    image: traefik
    restart: always
    command: >-
      --certificatesResolvers.default.acme.email=${ACME_EMAIL}
      --certificatesResolvers.default.acme.httpChallenge.entryPoint=http
      --entrypoints.http.address=:80
      --entrypoints.http.http.redirections.entryPoint.to=https
      --entrypoints.https.address=:443
      --providers.docker
      --providers.docker.exposedByDefault=false
    cpu_percent: 50
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:172.17.0.1
    volumes:
      - ${DATA_DIR}/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    links:
      - mariadb
      - redis
    environment:
      - MYSQL_DATABASE
      - MYSQL_HOST=mariadb
      - MYSQL_PASSWORD
      - MYSQL_USER
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN_NEXTCLOUD}
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=172.16.0.0/12
    volumes:
      - nccontent:/var/www/html
      - ${DATA_DIR}/nextcloud/config:/var/www/html/config
      - ${DATA_DIR}/nextcloud/data:/var/www/html/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NEXTCLOUD}`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=default
      - traefik.http.routers.nextcloud.middlewares=nextcloud-dav@docker,nextcloud-headers@docker
      - traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/
      - traefik.http.middlewares.nextcloud-headers.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.nextcloud-headers.headers.framedeny=true
      - traefik.http.middlewares.nextcloud-headers.headers.sslredirect=true
      - traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true
      - traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000

  nextcloud_cron:
    container_name: nextcloud_cron
    image: nextcloud
    restart: always
    links:
      - mariadb
      - redis
    entrypoint: >-
      sh -c '
        grep -q "preview:pre-generate" /var/spool/cron/crontabs/www-data ||
        echo "*/30 * * * * php -f /var/www/html/occ preview:pre-generate" >> /var/spool/cron/crontabs/www-data;
        /cron.sh
      '
    volumes:
      - nccontent:/var/www/html
      - ${DATA_DIR}/nextcloud/config:/var/www/html/config
      - ${DATA_DIR}/nextcloud/data:/var/www/html/data

  mariadb:
    container_name: mariadb
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    command: >-
      --binlog-format=ROW
      --transaction-isolation=READ-COMMITTED
    ports:
      - 3306:3306
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server --appendonly no --save ""

  samba:
    container_name: samba
    image: dperson/samba
    ports:
      #- 137:137/udp
      #- 138:138/udp
      - 139:139
      - 445:445
    environment:
      - GROUPID=33
      #- NMBD=1
      - RECYCLE=1
      - SHARE1
      - SHARE2
      - SHARE3
      - TZ
      - USERID=33
    volumes:
      - ${DATA_DIR}/nextcloud/data:/data:ro

  minidlna:
    container_name: minidlna
    image: vladgh/minidlna
    restart: always
    environment:
      - GUID=33
      - MINIDLNA_FRIENDLY_NAME=${HOSTNAME}
      - MINIDLNA_MEDIA_DIR_1
      - MINIDLNA_MEDIA_DIR_2
      - MINIDLNA_MEDIA_DIR_3
      - MINIDLNA_MEDIA_DIR_4
      - MINIDLNA_MEDIA_DIR_5
      - MINIDLNA_MEDIA_DIR_6
      - MINIDLNA_MEDIA_DIR_7
      - MINIDLNA_MEDIA_DIR_8
      - MINIDLNA_MEDIA_DIR_9
      - MINIDLNA_ROOT_CONTAINER
      - PUID=33
    network_mode: host
    volumes:
      - ${DATA_DIR}/nextcloud/data:/data:ro

  backup:
    container_name: backup
    image: mazzolino/restic
    hostname: ${HOSTNAME}
    restart: always
    cpu_percent: 50
    environment:
      - B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY
      - BACKUP_CRON=0 0 2 * * *
      - POST_COMMANDS_FAILURE
      - POST_COMMANDS_SUCCESS
      - PRE_COMMANDS=
          docker exec mariadb mysqldump -A |
          gzip > /data/mariadb.sql.gz
      - RESTIC_BACKUP_ARGS=
          --exclude '*.log'
          --exclude 'appdata_*'
          --exclude 'files_trashbin'
          --exclude 'updater-*'
          --exclude-if-present '.nobackup'
          --exclude-if-present 'ibdata1'
          --exclude-if-present 'platformio.ini'
          --tag local
      - RESTIC_FORGET_ARGS=
          --group-by tag
          --keep-daily 7
          --keep-weekly 5
          --keep-monthly 12
          --prune
      - RESTIC_PASSWORD
      - RESTIC_REPOSITORY
      - TZ
    volumes:
      - ${DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      - TZ
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 1 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nccontent:
