version: "2.4"
services:

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: always
    network_mode: host
    volumes:
      - /etc/hosts:/host:ro
      - ${DATA_DIR}/homeassistant:/config

  esphome:
    container_name: esphome
    image: esphome/esphome
    restart: always
    network_mode: host
    ports:
      - 6052:6052
    volumes:
      - ${DATA_DIR}/esphome:/config
    #devices:
      #- /dev/ttyUSB0

  grocy:
    container_name: grocy
    image: linuxserver/grocy
    restart: always
    volumes:
      - ${DATA_DIR}/grocy:/config/data

  deconz:
    container_name: deconz
    image: marthoc/deconz:stable
    restart: always
    network_mode: host
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - TZ
    volumes:
      - ${DATA_DIR}/deconz:/root/.local/share/dresden-elektronik/deCONZ

  paperless:
    container_name: paperless
    image: jonaswinkler/paperless-ng
    restart: always
    links:
      - redis
    ports:
      - 8000:8000
    environment:
      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_TIME_ZONE=${TZ}
    volumes:
      - ${DATA_DIR}/paperless/data:/usr/src/paperless/data
      - ${DATA_DIR}/paperless/data:/usr/src/paperless/media
      - ${DATA_DIR}/paperless/export:/usr/src/paperless/export
      - ${DATA_DIR}/paperless/consume:/usr/src/paperless/consume

  ssh_master:
    container_name: ssh_master
    image: alpine
    restart: always
    command: sh -c '
        adduser -DH satellite;
        apk --no-cache add dropbear openssh-client &&
        mkdir -p /etc/dropbear &&
        dropbear -EFjRsw -c /bin/false
      '
    ports:
      - "${SSH_MASTER_PORT}:22"
    volumes:
      - ${DATA_DIR}/dropbear:/etc/dropbear
      - /home/admin/.ssh/authorized_keys:/home/satellite/.ssh/authorized_keys:ro
