version: "2.4"
services:

  solar:
    container_name: solar
    image: docker.io/alpine
    security_opt: [ label=disable ]
    restart: always
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_BUCKET
      - INFLUXDB_HOST=influxdb:8086
      - INFLUXDB_ORG
      - INFLUXDB_TOKEN
      - KACO_HOST
      - SOLARLOG_HOST
      - SOLARLOG_PASSWORD
      - SOLARLOG_USER
      - SONNENSPEICHER_PASSWORD
      - SONNENSPEICHER_USER
      - TZ
    command: >-
      sh -c '
        apk --no-cache add curl jq tzdata &&
        while true; do
          sh kaco.sh;
          sh solarlog.sh;
          sh sonnenspeicher.sh;
          unset START_YEAR;
          sleep 300;
        done
      '
    working_dir: /app
    volumes:
      - ./solar:/app:ro

  influxdb:
    container_name: influxdb
    image: docker.io/influxdb:1.8
    security_opt: [ label=disable ]
    restart: always
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      # 1.8 compatibility
      - INFLUXDB_DB=${INFLUXDB_BUCKET}
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana
    security_opt: [ label=disable ]
    restart: always
    links:
      - influxdb
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    user: root
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
