version: "2.4"
services:

  solar:
    container_name: solar
    image: alpine
    restart: always
    links:
      - influxdb
    environment:
      - INFLUXDB_BUCKET
      - INFLUXDB_HOST=influxdb:8086
      - KACO_HOST
      - SOLARLOG_HOST
      - SOLARLOG_PASSWORD
      - SOLARLOG_USER
      - SONNENSPEICHER_PASSWORD
      - SONNENSPEICHER_USERNAME
      - START_YEAR
      - TZ
    command: >-
      sh -c '
        apk --no-cache add curl jq &&
        while true; do
          sh kaco.sh;
          sh solarlog.sh;
          sh sonnenspeicher.sh;
          unset START_YEAR;
          sleep 600;
        done
      '
    working_dir: /app
    volumes:
      - ./solar:/app:ro

  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    restart: always
    ports:
      - 8086:8086
