version: "2.4"
services:

  solar:
    container_name: solar
    image: alpine
    restart: always
    environment:
      - AUTH_NEXTCLOUD
      - DOMAIN_NEXTCLOUD
      - DATASET_CURRENT
      - DATASET_KACO
      - DATASET_SOLARLOG
      - DATASET_SONNENSPEICHER
      - SONNENSPEICHER_PASSWORD
      - SONNENSPEICHER_USERNAME
      - START_YEAR
      - TZ
      - URL_KACO
      - URL_SOLARLOG
    command: >-
      sh -c '
        apk --no-cache add curl jq &&
        while true; do
          sh kaco.sh;
          sh solarlog.sh;
          sh sonnenspeicher.sh;
          unset START_YEAR;
          sleep 600;
        done
      '
    working_dir: /app
    volumes:
      ./solar:/app:ro
