version: "2.4"
services:

  dnsmasq:
    container_name: dnsmasq
    image: alpine:3.12
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    cap_add:
      - NET_ADMIN
    entrypoint: >-
      sh -c '
        apk add --no-cache dnsmasq &&
        dnsmasq \
          --address=/${DOMAIN_NEXTCLOUD}/${DOMAIN_HOMEASSISTANT}/${DOMAIN_GROCY}/${LOCAL_IP} \
          --all-servers \
          --keep-in-foreground \
          --log-facility=- \
          --no-hosts \
          --no-resolv \
          --server=94.140.14.14 \
          --server=94.140.15.15
      '

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: always
    #network_mode: host
    ports:
      - 8123:8123
    volumes:
      - /etc/hosts:/host:ro
      - ${DATA_DIR}/homeassistant:/config

  esphome:
    container_name: esphome
    image: esphome/esphome
    restart: always
    network_mode: host
    ports:
      - 6052:6052
    volumes:
      - ${DATA_DIR}/esphome:/config
    #devices:
      #- /dev/ttyUSB0

  grocy:
    container_name: grocy
    image: linuxserver/grocy
    restart: always
    volumes:
      - ${DATA_DIR}/grocy:/config/data
  deconz:
    container_name: deconz
    image: marthoc/deconz:stable
    restart: always
    network_mode: host
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - TZ
    volumes:
      - ${DATA_DIR}/deconz:/root/.local/share/dresden-elektronik/deCONZ
