targetConfigs:
- url: https://github.com/escoand/dockerfiles.git
  branch: kube
  kube:
  - name: kube
    targetPath: kube.cloud
    schedule: "*/1 * * * *"
    pullImage: true
prune:
  All: true
  Volumes: false
  schedule: "*/1 * * * *"