apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: caddy
        image: docker.io/library/caddy:2.7.6-alpine
        ports:
        - containerPort: 80
          hostPort: 8080
        - containerPort: 443
          hostPort: 8443
        - containerPort: 443
          hostPort: 8443
          protocol: UDP
        command:
          - /bin/sh
          - -c
          - |-
            echo '
            {$NEXTCLOUD_DOMAIN} {
              #log
              redir /.well-known/carddav /remote.php/dav/ 301
              redir /.well-known/caldav  /remote.php/dav/ 301
              reverse_proxy nextcloud:80
            }
            {$REDIR_DOMAIN} {
              redir {$REDIR_TARGET}
            }
            {$DOZZLE_DOMAIN} {
              #basic_auth {
              #  {$DOZZLE_USER} {$DOZZLE_PASSWORD}
              #}
              reverse_proxy dozzle:8080
            }
            ' | exec caddy run --config - --adapter caddyfile
        livenessProbe:
          # httpGet uses curl, which is not available
          tcpSocket:
            port: 80
        env:
        - name: DOZZLE_DOMAIN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: dozzle_domain
        - name: DOZZLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: dozzle_password
        - name: DOZZLE_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: dozzle_user
        - name: NEXTCLOUD_DOMAIN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: nextcloud_domain
        - name: REDIR_DOMAIN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: redir_domain
        - name: REDIR_TARGET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: redir_target
