apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: caddy
        image: docker.io/library/caddy:2.7.6-alpine
        ports:
        - containerPort: 80
          hostPort: 8080
        - containerPort: 443
          hostPort: 8443
        - containerPort: 443
          hostPort: 8443
          protocol: UDP
        command:
          - /bin/sh
          - -c
          - |-
            echo '
            :8081 { respond }
            {$NEXTCLOUD_DOMAIN} {
              log
              redir /.well-known/carddav /remote.php/dav/ 301
              redir /.well-known/caldav  /remote.php/dav/ 301
              reverse_proxy nextcloud:80 {
                #header_up Host {remote_host}
              }
            }
            {$REDIR_DOMAIN} {
              redir {$REDIR_TARGET}
            }
            ' | exec caddy run --config - --adapter caddyfile
        livenessProbe_:
          httpGet:
            path: /
            port: 8081
        env:
        - name: NEXTCLOUD_DOMAIN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: nextcloud_domain
        - name: REDIR_DOMAIN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: redir_domain
        - name: REDIR_TARGET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: redir_target
