apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: caddy
        image: docker.io/library/caddy:2.7.6-alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 443
          protocol: UDP
        command:
          - /bin/sh
          - -c
          - |-
            echo '{$NEXTCLOUD_DOMAIN} {
              reverse_proxy nextcloud:80
              redir /.well-known/caldav  /remote.php/dav/ 301
              redir /.well-known/carddav /remote.php/dav/ 301
            }' | exec caddy run --config - --adapter caddyfile
        env:
        - name: NEXTCLOUD_DOMAIN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: nextcloud_domain