apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  template:
    spec:
    metadata:
      annotations:
        io.podman.annotations.userns: keep-id
      containers:
      - name: nextcloud
        image: docker.io/library/nextcloud:28.0.4
        resources:
          limits:
            memory: 2Gi
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secrets
              key: nextcloud_db_name
        - name: MYSQL_HOST
          value: mariadb
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: nextcloud_db_password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: nextcloud_db_user
        - name: NEXTCLOUD_INIT_HTACCESS
          value: "TRUE"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: nextcloud_domain
        - name: NEXTCLOUD_UPDATE
          value: "1"
        - name: REDIS_HOST
          value: redis
        - name: TRUSTED_PROXIES
          value: 10.88.0.0/16
        envFrom:
        - secretRef:
            name: proxy
            optional: true
        volumeMounts:
        - name: nextcloud_apps
          mountPath: /var/www/html/custom_apps:z
        - name: nextcloud_config
          mountPath: /var/www/html/config:z
        - name: nextcloud_data
          mountPath: /var/www/html/data:z
      volumes:
      - name: nextcloud_apps
        persistentVolumeClaim:
          claimName: nextcloud_apps
      - name: nextcloud_config
        persistentVolumeClaim:
          claimName: nextcloud_config
      - name: nextcloud_data
        persistentVolumeClaim:
          claimName: nextcloud_data
