name: cloud-init

on:
  pull_request:
  push:

jobs:
  test-cloudinit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          set -ex
          sudo apt-get -qy update
          sudo apt-get -qy install cloud-image-utils cloud-init qemu-system-x86 wget
          wget https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
          cloud-localds seed.img config.yaml
          kvm \
            -m 512 \
            -net nic \
            -net user \
            -redir tcp:2222::22 \
            -drive file=AlmaLinux-9-GenericCloud-latest.x86_64.qcow2,if=virtio,format=qcow2 \
            -drive file=seed.img,if=virtio,format=raw
          ssh -p 2222 localhost 'cat /var/log/cloud-init.log' |
          cloud-init analyze blame -i -
