on: push

jobs:
  test-commit:
    name: Test commit
    runs-on: ubuntu-24.04
    steps:
      # setup
      - name: Install deps
        run: |
          sudo apt-get update -qy &&
          sudo apt-get install -qy podman>=4.4
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Podman socket
        run: systemctl --user start podman.socket
      # test kube config
      - name: Test kube config
        run: ./test-kube.sh
        timeout-minutes: 1