on: push

jobs:
  test-commit:
    name: Test commit
    runs-on: ubuntu-24.04
    steps:
      - name: Install deps
        run: |
          sudo apt-get update -qy &&
          sudo apt-get install -qy podman>=4.4
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Podman socket
        run: systemctl --user start podman.socket
      - name: Patch pods for testing
        run: |-
          sed -i \
              -e '/^[[:blank:]]*env:/ {' \
              -e 'a\        - { name: NEXTCLOUD_ADMIN_USER, value: admin }' \
              -e 'a\        - { name: NEXTCLOUD_ADMIN_PASSWORD, value: admin }' \
              -e '}' \
              kube/nextcloud.yaml &&
          sed -i \
              -e "s|/run/user/1000/|${XDG_RUNTIME_DIR:-/run/user/1000}/|" \
              kube/*.yaml
      - name: Create pods
        run: |-
          find init/ -name 'secrets.*.yaml' -exec podman kube play {} \; &&
          find kube/ -name '*.yaml' -exec podman kube play --quiet --start=false {} \;
      - name: Create databases
        run: |-
          podman pod start mariadb-pod &&
          podman wait --condition healthy mariadb-pod-mariadb &&
          podman secret ls --format '{{.Name}}' |
          while read -r SECRET; do
            podman secret inspect "$SECRET" --showsecret --format '{{.SecretData}}' |
            sed -n 's/_db_name:.*//Ip' |
            xargs -ti ./db_usr_pwd.sh {} "$SECRET"
          done
      - name: Start pods
        run: podman pod start -a
      - name: Wait for healthy state
        run: |-
          find kube/ -name '*.yaml' |
          sed 's|^.*/\(.*\)\.yaml|\1-pod-\1|' |
          xargs -t podman wait --condition healthy
