LoadModule auth_openidc_module /usr/lib/apache2/modules/mod_auth_openidc.so

OIDCProviderMetadataURL https://${OIDC_DOMAIN}/.well-known/openid-configuration
OIDCClientID ${OIDC_CLIENT}
OIDCClientSecret ${OIDC_SECRET}
OIDCRedirectURI /admin/callback
OIDCCryptoPassphrase ${OIDC_SECRET}
OIDCXForwardedHeaders X-Forwarded-Proto

#Allow from all

<Location /admin/>
AuthType openid-connect
Require valid-user
</Location>